### ISSUE TITLE
This or that now temp. removed

### ISSUE THREAD

**Issue by mahadi22** [gabrielmdu/Alienware-Arena-Level-Farm#1]
https://eu.alienwarearena.com/ucf/show/1733126/boards/site-bug-reports/ForumPost/this-or-that-temporarily-suspended

as its says in forum, they temporarily removed this or that, so maybe you can give choice to skipped this or that like choice for posting on forum

**Comment by gabrielmdu** [comment]
Thanks for reporting. I'll work on it today.
