### ISSUE TITLE
Error after login and quitting

### ISSUE THREAD

**Issue by mahadi22** [gabrielmdu/Alienware-Arena-Level-Farm#2]
today, awalf didnt work, after login and succesfull the program will stop imediately

ss: http://mahadi.noip.me/ss/1498575633-z.png

windows 10-64, 
firefox 54.0-32,
geckodriver v0.16.1-32,
Python 2.7.12 (v2.7.12:d33e0cf91556)

**Comment by gabrielmdu** [comment]
Thanks for the report. I'll check this pretty soon.

**Comment by gabrielmdu** [comment]
@mahadi22 , it seems they removed This or That for good. I removed the elements related to ToT from the script and it should run fine now. Let's hope they create something new to give more ARP points.
