### ISSUE TITLE
becarefull for bot trap with specific word

### ISSUE THREAD

**Issue by mahadi22** [gabrielmdu/Alienware-Arena-Level-Farm#3]
now the site have a trap to bot who post this word

"Thanks for the News."
"Thanks for the info."
"Good News"
"Thank you" 
"Good Game"
"GG"
"Nice"
"Cool"

just a warning for anyone who use this
source: https://eu.alienwarearena.com/ucf/show/1780828/boards/gaming-news/News/a-new-game-called-bot-trap

**Comment by gabrielmdu** [comment]
Thanks for the heads up. I'll delete the content in the _posts.txt_ file and warn the user to write its own sentences.

**Comment by gabrielmdu** [comment]
I just modified the script to warn the user about the posts file. Now you need to write your own posts.
